### ISSUE TITLE
SyntaxError: invalid syntax  !!!

### ISSUE THREAD

**Issue by sydoluciani** [plone/plone.staticresources#116]
Starting [Plone docker container](https://github.com/plone/plone.docker/issues/145) throw below Syntax Errors:

```
File "/plone/buildout-cache/eggs/plone.staticresources-1.3.2-py3.8.egg/plone/staticresources/static/components/jqtree/_entries/insert.py", line 44
    print 'rename %s to %s' % (old_filename, new_filename)

SyntaxError: invalid syntax
```

**Comment by mauritsvanrees** [comment]
This is when running `buildout`, right?
This is harmless. See the [explanation](https://docs.plone.org/manage/troubleshooting/buildout.html#buildout-and-syntaxerrors).
Well, the explanation is for a slightly different situation, but it comes down to the same thing. This file needs to be included in the distribution, but is not actually used in production.

**Comment by sydoluciani** [comment]
Hi @mauritsvanrees , you are right, it is a harmless syntax error because the print statement is only for information and log output but the syntax error is due to missing parantheses, adding parantheses should fix the problem. Python 2.7 accepts print statement with and without parantheses, but to be compatible with Python 3, print statement must have paranthesis.

**Comment by mauritsvanrees** [comment]
I know.
But the file is [here in the source tree](https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/static/components/jqtree/_entries/insert.py) and it is automatically added because we somewhere depend on [jqtree](https://github.com/plone/plone.staticresources/blob/master/package.json#L10).
So when this is fixed in `jqtree` it will be fixed here as well.

BTW, I have not got the faintest idea of what `jqtree` actually is and what this file does. And there may be a newer version already that fixes this. But I can't imagine that this has any influence at all on how Plone runs.

**Comment by sydoluciani** [comment]
@mauritsvanrees You are right, [jqTree](https://github.com/mbraak/jqTree) is a different package that has been embeded in Plone, and its new version of [insert.py](https://github.com/mbraak/jqTree/blob/dev/_entries/insert.py#L44) has fixed the issue. so upgrading jqtree in plone should fix the issue, however I am not sure how Plone manages JavaScript installtion or upgrade. one need to fork, change the version in package.json and see if it upgrades to the latest package, or maybe it is afake, and one need to copy the new jqtree and replace the old one.

[jqtree](http://mbraak.github.io/jqTree/#demo) is to produce menu in website based on json data.

**Comment by sydoluciani** [comment]
@mauritsvanrees jqtree might be moved to Volto some time in future if Volto is going to be the default front end, but until then, these files should be maintained. 

Like you said, it is only a syntax error in print statement and probably not worth the upgrade, the upgrade might break some menus in Plone, but it is good to know what is the source of problem. now we know there is a jqtree to produce menu 😄 

Thanks for the reply and following up.
