### ISSUE TITLE
typo in bundlename

### ISSUE THREAD

**Issue by petschki** [plone/plone.staticresources#121]
upgrade profile 11 has a typo in the bundlename:

https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/upgrades/profiles/11/registry.xml#L24

that's why you get a completely new bundle called `resourceregistryt` after upgrading

**Comment by mauritsvanrees** [comment]
Oops, that extra 't' was my typo. Thanks for fixing.
I have lived in Rotterdam for half my life and we often add an extra 't' at the end of words, maybe that explains it. ;-)

We may need to update the timestamp for the bundle without the typo. But I am not sure my original timestamp update was really needed. After a change in mockup, it is hard to tell for me which bundle or bundles in staticresources need rebuilding.
