### ISSUE TITLE
Do we need all components in the release?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.staticresources#127]
The `plone.staticresources` release is big. I have just released [1.4.2](https://pypi.org/project/plone.staticresources/1.4.2/#files) which is about 26 MB. 1.4.1 was even 36 MB.
Does it make sense to remove most of [`src/plone/staticresources/static/components`](https://github.com/plone/plone.staticresources/tree/1.4.2/src/plone/staticresources/static/components) from the release? Or is that somehow used?
The `bootstrap-icons` directory [is needed](https://github.com/plone/plone.staticresources/blob/1.4.2/src/plone/staticresources/configure-resources.zcml#L14), but that seems about it. Or is the rest needed when you enable development mode and start building TTW?

If the rest can be removed, it could be done like this in `MANIFEST.in`:

```
graft src/plone
prune src/plone/staticresources/static/components
graft src/plone/staticresources/static/components/bootstrap-icons/icons
```

That brings it down to about 7 MB.

**Comment by thet** [comment]
@mauritsvanrees the resources are all registered in the registry. The reason for including them is to allow through the web compilation of JavaScript and CSS bundles, for whoever uses it.

In Plone 6 with ES6 we do not need any of them and only include the compiled bundle.

**Comment by mauritsvanrees** [comment]
Thanks for the clarification!
