### ISSUE TITLE
Upgrade TinyMCE to address GHSA-27gm-ghr9-4v95

### ISSUE THREAD

**Issue by nutjob4life** [plone/plone.staticresources#129]
Another vulnerability scan has shown that the TinyMCE component in plone.staticresources suffers fro [Github vulnerabiltiy GHSA-27gm-ghr9-4v95](https://github.com/advisories/GHSA-27gm-ghr9-4v95). The suggested mitigation is to upgrade to TinyMCE 4.9.7 or 5.1.4.

The [Prisma Cloud](https://www.paloaltonetworks.com/prisma/cloud) scan details are as follows:

- Vulnerability ID: GHSA-27gm-ghr9-4v95
- Severity: high
- Package: tinymce
- Version: 4.6.2
- Fix status: Fixed in 5.1.4, 4.9.7

**Comment by frapell** [comment]
We are now on 5.10.2, I believe this can be closed
