### ISSUE TITLE
Problem with fontello resources with 1.4.3 version

### ISSUE THREAD

**Issue by cekk** [plone/plone.staticresources#162]
I've updated my Plone 5.2.4 site to the new 5.2.5 and made the upgrade-step.

The site is published as "http://my-site.com/api" (with **/api** because it's Volto's backend).
All resources are loaded correctly (with **/api/**), except fontello ones: they don't have **/api** in the url and are loaded on a wrong context (that is the the Volto instance).

I think that could be related to recent changes made [here](https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/static/plone-fontello.less#L1).

Could be solved removing the "/"? Something like this:

`@fontsPrefix: '++plone++static/fonts/';`

**Comment by cekk** [comment]
@agitator could have the answer ;)

**Comment by agitator** [comment]
Moved the fontello fonts to their own bundle, to not include them inlined in every bundle.
Not sure how that should affect volto...?

**Comment by nzambello** [comment]
Volto is not affected, but a Plone site used as Volto backend is published under `/api`
Fontello resources are loaded as  `/......` so the browser is asking to Volto something that just doesn't exist.

**Comment by agitator** [comment]
I recall that I had to play around to make it work for dev and production... using `/` did solve it.
Not sure what your setup exactly looks like...should we discuss it on discord #classic-ui?
If those paths can't be resolved in your case, maybe inline that font into the css?

**Comment by agitator** [comment]
@cekk as we discussed ... best way would be to do a manual bundle... those font bundles won't change anyway

- don't use plone-compile for that
- create a little compile-script (probably just a one liner) to inline the fonts 
- add some comments about the process into the readme

Only downside is that all types (ttf/eot/...) of that webfont are loaded then

cc @thet

**Comment by sneridagh** [comment]
@agitator so the upgrade step is broken? do the vanilla installation work?

**Comment by sneridagh** [comment]
@agitator at first I couldn't get a full grasp of the thing, even when we talked about it, but I think now I did:
Login at: https://6.demo.plone.org/api

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/486927/132992939-f5781da5-69fb-439f-b1d8-f011305caa0f.png">

Regardless that's a Volto in the root level, which it's not relevant in the issue (Volto simply does not care), this will break on any site that does not have an instance in the root level, thus, won't be able to deliver the resource properly. 

Isn't more sensible serve and get the assets relatively (like @cekk suggested?).

**Comment by erral** [comment]
This is because of this commit: 

https://github.com/plone/plone.staticresources/commit/0228cd7ccceba2fed4ae7ff9b43459defbcd2957

Here we are requesting the font to be loaded from the root of the site.

**Comment by thet** [comment]
Fixed via: https://github.com/plone/plone.staticresources/pull/168

**Comment by cekk** [comment]
@thet i'm confused.

#172 should be the pr that generated 1.4.4 version, right?
But if i try to download that from pypi, i see that all fontello compiled resources still have "/++plone++static" and not "++plone++static"

**Comment by thet** [comment]
Fixed by: https://github.com/plone/plone.staticresources/pull/207
