### ISSUE TITLE
Add upgrade steps for last_compilation dates

### ISSUE THREAD

**Issue by thet** [plone/plone.staticresources#19]
Currently for a new bundle build we need to update the ``last_compilation`` dates in bundles.xml and additionally in plone.app.upgrade.
This process is tedious because for each fix you immediately have to track two distinct repositories.

@ale-rt @mauritsvanrees what to you think of moving all ``last_compilation`` date updates from plone.app.upgrade into here? Then we'd only need to update that in here which makes the upgrade process a lot simpler I guess.

**Comment by ale-rt** [comment]
I am +1. 
It also follows the same philosophy of PLIP https://github.com/plone/Products.CMFPlone/issues/1653 to centralize in this package everything that is related to static resources.
In some cases also other registry records might need to be updated if some of these files needs an update: https://github.com/plone/plone.staticresources/tree/master/src/plone/staticresources/profiles/default/registry

**Comment by mauritsvanrees** [comment]
Makes sense. So:

1. Create upgrade steps in `plone.staticresources`.
2. Add the `plone.staticresources:default` profile to the `ADDON_LIST` in [`CMFPlone.MigrationTool`](https://github.com/plone/Products.CMFPlone/blob/5.2rc1/Products/CMFPlone/MigrationTool.py#L87-L102) so all its available upgrade steps are always automatically applied during a `@@plone-upgrade`.

That should work.

**Comment by thet** [comment]
Done with: https://github.com/plone/Products.CMFPlone/pull/2976
Thanks for the pointer @mauritsvanrees !
