### ISSUE TITLE
Py3-coredev: Py3 incompatible "print" statements

### ISSUE THREAD

**Issue by d-maurer** [plone/plone.staticresources#20]
The current (Plone) "coredev" binds in `plone.staticresources == 1.0.0` and this uses Py3 incompatible `print` statements in:
* static/components/cs-jqtree-contextmenu/node_modules/jqtree/_entries/renumber.py", line 36
* static/components/cs-jqtree-contextmenu/node_modules/jqtree/_entries/insert.py", line 44

**Comment by thet** [comment]
These are Python scripts inside node_modules and not used by us. We should probably exclude any python in node_modules via .gitignore

**Comment by zopyx** [comment]
At least the print statement should be replaced with print() function calls...the most easy way to fix this issue.

**Comment by jensens** [comment]
Well, this is third party code. IMO we can just remove this files in here.
