### ISSUE TITLE
Deployments not rooted fail to load the Fontello icons

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.staticresources#203]
See https://github.com/plone/plone.staticresources/pull/175
Related: https://github.com/plone/plone.staticresources/issues/162 https://github.com/plone/plone.staticresources/pull/168 and https://github.com/plone/plone.staticresources/pull/171

## Plone 6.0.0a3

Just after start the site: 

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/486927/160294487-98b0e915-f90f-4a35-91ef-7924040e8838.png">

This is still not working in a not rooted deployed site. 

## Plone 5.2.7

Also present in 5.2.7 that I upgraded some days ago.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/486927/160294701-8e3bd771-842d-4f6f-9caf-8f44d6acb119.png">

Can we give to this priority? I'd like to figure this out and fix it right away. I can help whenever necessary.

/cc @mauritsvanrees @tisto @erral @cekk @ericof

**Comment by sneridagh** [comment]
I can confirm that 5.2.6 and 5.2.5 have this bug present there as well. 5.2.4 do not.

**Comment by yurj** [comment]
See also https://github.com/plone/mockup/issues/1102 https://github.com/plone/plonetheme.barceloneta/issues/261 and https://discord.com/channels/786421998426521600/787254601656827924/913696217148567553

**Comment by thet** [comment]
Fixed by: https://github.com/plone/plone.staticresources/pull/207
