### ISSUE TITLE
Where is the script plone-compile-resources in 2.0.0a3?

### ISSUE THREAD

**Issue by Arkusm** [plone/plone.staticresources#219]
The documentation says the script `plone-compile-resources` would be available in the bin directory of a default Plone installation. To my knowledge it was installed up to v 2.0.0a2 with buildout as follows:

```
[compileresources]
recipe = zc.recipe.egg
eggs =
    plone.staticresources
scripts = plone-compile-resources
```

Now in version 2.0.0a3 it seems to be not installable like this and there is no corresponding entry point:

```
...
Installing compileresources.
Could not generate script 'plone-compile-resources' as it is not defined in the egg entry points.
...
```
How can `plone-compile-resources` be installed in Plone 6(.0.0a3 /a4)?

**Comment by petschki** [comment]
README got updated ... I'll close this
