### ISSUE TITLE
Vulnerabilities found

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.staticresources#3]
After fixing #2 (PR coming) ./bin/plone-compile-resources installs the packages properly but reports some vulnerabilities:
```
[ale@emily plone.staticresources]$ ./bin/plone-compile-resources 
Setup npm env
Running command: npm install
...
found 5 vulnerabilities (4 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
...
```

**Comment by gforcada** [comment]
This is probably obsolete already, though new vulnerabilities might be around.

GitHub has some bots for these things, right?
