### ISSUE TITLE
Upgrade bootstrap icons to v1.11.3

### ISSUE THREAD

**Issue by 1letter** [plone/plone.staticresources#343]

**Comment by petschki** [comment]
The version got updated a while ago here https://github.com/plone/mockup/commit/a7a4c7a5a08ba9c244ffd2ecbf49c0be5eab7bec

**Comment by petschki** [comment]
Also for `5.1.x` https://github.com/plone/mockup/commit/73c874fbdc9d276ef119cdb86a9bd48f14e50997
