### ISSUE TITLE
Cannot remove upload tab from link popup

### ISSUE THREAD

**Issue by parruc** [plone/plone.staticresources#49]
Setting upload false into data-pat-tinymce does not remove the upload button

**Comment by parruc** [comment]
The problem seems to be that we have 2 "upload" keys so the label overrides the boolean one

`    generateModalHtml: function() {
      return this.template({
        options: this.options,
        upload: this.options.upload,
        text: this.options.text,
        insertHeading: this.options.text.insertHeading,
        insertImageHelp: this.options.text.insertImageHelp,
        upload: this.options.text.upload,
        insertLinkHelp: this.options.text.insertLinkHelp,`

**Comment by thet** [comment]
Fixed with: https://github.com/plone/mockup/pull/928
