### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.staticresources#7]
# Important things that I found undocumented in the process

## Prerequisites to build the bundle using the ./bin/plone-compile-resources script

A modern node environment with grunt and yarn.
An up to date Plone 5.2 installation with a pretty clean website.

## Development flow

This is based on my experience with the package

In order to have the resources available/updated we should run `yarn install` in the package root, e.g.:
```
[ale@emily plone.staticresources]$ yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.31s.
```

This will create the proper resources in `src/plone/staticresources/static/components/`.
The relevant resources should be pushed to allow TTW bundling and customization in Plone's resource registry control panel.

Whenever you want to add a new resource you have to:
1) add an entry in to this package generic setup profile folder `src/plone/staticresources/profiles/default/registry/resources.xml`
2) you need to create an upgrade profile in plone.app.upgrade that applies the registry modification
3) you need to run the upgrade step to have a site with the proper registry configuration.
4) run the script `./bin/plone-compile-resources`. This assumes your properly configure site id is Plone.

Maybe some other method is possible but I am not aware of it at the moment.

Once this has been done the changes in this package should be pushed in a branch as usual in order to make a PR.

**Comment by gforcada** [comment]
For Plone 6 the approach has changed quite a bit, at least that's what I read, I'm far from an expert, and at least the README provides a few hints on how to work with it.
