### ISSUE TITLE
Ready and synced for 5.2.2?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.staticresources#80]
I am working on a Plone 5.2.2 release, see https://github.com/plone/Products.CMFPlone/issues/3119.

Can anyone tell me if `mockup` and `plone.staticresources` are in sync?
I can make releases of these (fine if someone else does this), but I am not the best person to know if the master branches are okay.

**Comment by thet** [comment]
@mauritsvanrees I'll have a look into this.

**Comment by thet** [comment]
Ref: https://github.com/plone/plone.staticresources/pull/82

**Comment by petschki** [comment]
see #86 before release!

**Comment by vincentfretin** [comment]
Please wait for
- https://github.com/plone/Products.CMFPlone/issues/2953
- https://github.com/plone/Products.CMFPlone/issues/3120
- https://github.com/plone/Products.CMFPlone/issues/3124
to be closed.

**Comment by vincentfretin** [comment]
The release that was made 8 years ago contains regressions. We will need to do a new release.
Blocking issue remaining plone/Products.CMFPlone#2953

**Comment by vincentfretin** [comment]
I closed plone/Products.CMFPlone#2953
We can do a new release now.

**Comment by vincentfretin** [comment]
https://github.com/plone/plone.staticresources/pull/87

**Comment by vincentfretin** [comment]
plone.staticresources 1.3.0 was released with mockup 3.2.0 :champagne:
